services:
 nginx:
   image: nginx
   ports:
    - "82:80"
   volumes:
    - ./Docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    - .:/var/www/html
   restart: always
   depends_on:
    - php-fpm
    - postgres

 php-fpm:
   image: php:8.1-fpm
   build: ./Docker/php
   volumes:
    - .:/var/www/html

 postgres:
   image: postgres:13.1
   environment:
    POSTGRES_USER: user
    POSTGRES_PASSWORD: pass
    POSTGRES_DB: mydb
   ports:
    - "54322:5432"






